/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed1;
  GtkWidget *nom;
  GtkWidget *ville;
  GtkWidget *region;
  GtkWidget *capacite;
  GtkWidget *telephone;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *afficher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *type_ETS;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed1);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 136, 72);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  ville = gtk_entry_new ();
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed1), ville, 136, 136);
  gtk_widget_set_size_request (ville, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ville), 8226);

  region = gtk_entry_new ();
  gtk_widget_show (region);
  gtk_fixed_put (GTK_FIXED (fixed1), region, 136, 224);
  gtk_widget_set_size_request (region, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (region), 8226);

  capacite = gtk_entry_new ();
  gtk_widget_show (capacite);
  gtk_fixed_put (GTK_FIXED (fixed1), capacite, 136, 312);
  gtk_widget_set_size_request (capacite, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (capacite), 8226);

  telephone = gtk_entry_new ();
  gtk_widget_show (telephone);
  gtk_fixed_put (GTK_FIXED (fixed1), telephone, 136, 384);
  gtk_widget_set_size_request (telephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephone), 8226);

  label1 = gtk_label_new (_("NOM_ETS"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 72);
  gtk_widget_set_size_request (label1, 96, 25);

  label2 = gtk_label_new (_("Ville"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 136);
  gtk_widget_set_size_request (label2, 72, 25);

  label3 = gtk_label_new (_("Region"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 224);
  gtk_widget_set_size_request (label3, 72, 25);

  label4 = gtk_label_new (_("Capacite"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 24, 312);
  gtk_widget_set_size_request (label4, 96, 25);

  label5 = gtk_label_new (_("Telephone"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 24, 384);
  gtk_widget_set_size_request (label5, 96, 25);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 200, 544);
  gtk_widget_set_size_request (ajouter, 109, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 360, 544);
  gtk_widget_set_size_request (afficher, 100, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (afficher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("type_ETS"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 24, 272);
  gtk_widget_set_size_request (label11, 96, 16);

  type_ETS = gtk_entry_new ();
  gtk_widget_show (type_ETS);
  gtk_fixed_put (GTK_FIXED (fixed1), type_ETS, 136, 272);
  gtk_widget_set_size_request (type_ETS, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (type_ETS), 8226);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ville, "ville");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, region, "region");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, capacite, "capacite");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, telephone, "telephone");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image5, "image5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, type_ETS, "type_ETS");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *actualiser;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *retour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 120, 136);
  gtk_widget_set_size_request (treeview1, 300, 200);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser, 336, 440);
  gtk_widget_set_size_request (actualiser, 117, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed2), retour, 184, 440);
  gtk_widget_set_size_request (retour, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, retour, "retour");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label8, "label8");

  return fenetre_afficher;
}

